//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gordago.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gordago.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] COCycleLines {
            get {
                object obj = ResourceManager.GetObject("COCycleLines", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COFibo {
            get {
                object obj = ResourceManager.GetObject("COFibo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COFiboArcs {
            get {
                object obj = ResourceManager.GetObject("COFiboArcs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COFiboExp {
            get {
                object obj = ResourceManager.GetObject("COFiboExp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COFiboFan {
            get {
                object obj = ResourceManager.GetObject("COFiboFan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COHorLine {
            get {
                object obj = ResourceManager.GetObject("COHorLine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COLabel {
            get {
                object obj = ResourceManager.GetObject("COLabel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CORectangle {
            get {
                object obj = ResourceManager.GetObject("CORectangle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COTrendLine {
            get {
                object obj = ResourceManager.GetObject("COTrendLine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COTriangle {
            get {
                object obj = ResourceManager.GetObject("COTriangle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COVerLine {
            get {
                object obj = ResourceManager.GetObject("COVerLine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] COVHLine {
            get {
                object obj = ResourceManager.GetObject("COVHLine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_cycle_lines {
            get {
                object obj = ResourceManager.GetObject("m_co_cycle_lines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_fibo {
            get {
                object obj = ResourceManager.GetObject("m_co_fibo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_fibo_arcs {
            get {
                object obj = ResourceManager.GetObject("m_co_fibo_arcs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_fibo_expansion {
            get {
                object obj = ResourceManager.GetObject("m_co_fibo_expansion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_fibo_fan {
            get {
                object obj = ResourceManager.GetObject("m_co_fibo_fan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_fibo_timezone {
            get {
                object obj = ResourceManager.GetObject("m_co_fibo_timezone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_horline {
            get {
                object obj = ResourceManager.GetObject("m_co_horline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_label {
            get {
                object obj = ResourceManager.GetObject("m_co_label", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_rectangle {
            get {
                object obj = ResourceManager.GetObject("m_co_rectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_tradeline {
            get {
                object obj = ResourceManager.GetObject("m_co_tradeline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_trendline {
            get {
                object obj = ResourceManager.GetObject("m_co_trendline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_triangle {
            get {
                object obj = ResourceManager.GetObject("m_co_triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_co_vertline {
            get {
                object obj = ResourceManager.GetObject("m_co_vertline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m_col_verhorline {
            get {
                object obj = ResourceManager.GetObject("m_col_verhorline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] VCHorsScale {
            get {
                object obj = ResourceManager.GetObject("VCHorsScale", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
